# Generated by Django 5.0.3 on 2024-03-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicwebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Date_of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
