# Generated by Django 5.0.3 on 2024-03-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicwebApp', '0003_rename_age_form_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='age',
            field=models.IntegerField(),
        ),
    ]
